name: qrcodescavengerhuntapp

services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 120s
      timeout: 30s
      retries: 5

  flyway:
    image: flyway/flyway:9
    container_name: flyway_migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=/run/secrets/db_password
      - FLYWAY_SCHEMAS=public
    secrets:
      - db_password
    volumes:
      - ./sql/migrations:/flyway/sql
    command: -baselineOnMigrate=true migrate


volumes:
  db-data:
secrets:
  db_password:
    file: [REDACTED]