spring.application.name=qrcodescavengerhunt

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DRIVE_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=none

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}

logging.level.org.springframe.web=DEBUG
logging.level.com.sourcream=DEBUG


